version: '3.8'

services:
  frontend:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: http://book-advisor-be-app:8090
    ports:
      - "3000:3000"
    env_file:
      - .env.docker